#!/usr/bin/env bash
#
# Liberty Next — install helper.
#
# Generates .env with secure random secrets (no ``$`` chars, no compose-substitution
# footguns), then brings up the chosen Docker Compose layout. Refuses to overwrite an
# existing .env — re-runs are idempotent only when the .env is already in place.
#
# Usage:
#   ./install.sh                # interactive — asks light vs full
#   ./install.sh light          # single container, SQLite
#   ./install.sh full           # 5 services (Traefik + pg + pgadmin + portainer)
#   ./install.sh prepare        # generate .env only — don't start anything
#
# Re-running:
#   .env already present + stack up → no-op (use ``docker compose pull && up -d`` to upgrade).
#   .env already present + stack down → starts the stack with the existing .env.
#   .env missing → generates a fresh one + starts.
set -euo pipefail

# ── colours ───────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; NC=''
fi

info()  { printf "${BLUE}▸${NC} %s\n" "$*"; }
ok()    { printf "${GREEN}✔${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}!${NC} %s\n" "$*"; }
err()   { printf "${RED}✗${NC} %s\n" "$*" >&2; }
die()   { err "$*"; exit 1; }

cd "$(dirname "$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null || echo "$0")")"

# ── prerequisites ─────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker is not installed (https://docs.docker.com/engine/install/)"
docker compose version >/dev/null 2>&1 \
  || die "docker compose v2 is not available (try: docker compose version)"

# ── parse args ────────────────────────────────────────────────────────────────
LAYOUT="${1:-}"
case "$LAYOUT" in
  ""|light|full|prepare) ;;
  *) die "Unknown argument: $LAYOUT (expected: light | full | prepare)" ;;
esac

if [ -z "$LAYOUT" ]; then
  echo
  printf "${BOLD}Liberty Next — install${NC}\n"
  echo
  echo "Pick a layout:"
  echo "  1) light  — single container, SQLite DB (trial / demo)"
  echo "  2) full   — Traefik + liberty-next + Postgres + pgAdmin + Portainer (production)"
  echo
  read -r -p "Choose [1/2]: " choice
  case "$choice" in
    1) LAYOUT=light ;;
    2) LAYOUT=full ;;
    *) die "Invalid choice" ;;
  esac
fi

# ── helpers ───────────────────────────────────────────────────────────────────
# Generate a URL-safe-ish random string with NO ``$`` chars (so compose substitution
# never eats part of the value). 32 bytes → 64 hex chars; we use base32 here for shorter
# but case-insensitive-safe output. openssl is on every distro that has docker installed.
gen_secret() {
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes" | tr -d '\n=$+/' | head -c "$bytes"
  else
    head -c "$((bytes * 2))" /dev/urandom | base64 | tr -d '\n=$+/' | head -c "$bytes"
  fi
}

# ── .env generation ───────────────────────────────────────────────────────────
ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — keeping it. Delete it first to regenerate."
else
  info "Generating .env with random secrets…"

  LIBERTY_JWT_SECRET="$(gen_secret 48)"
  LIBERTY_MASTER_KEY="$(gen_secret 32)"
  POSTGRES_PASSWORD="$(gen_secret 24)"
  PGADMIN_PASSWORD="$(gen_secret 16)"
  LIBERTY_ADMIN_PASSWORD="$(gen_secret 16)"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Every secret below was generated with 'openssl rand' — none contain '\$' so they
# pass through docker-compose substitution untouched.

# ── REQUIRED ───────────────────────────────────────────────────────────────
LIBERTY_JWT_SECRET=${LIBERTY_JWT_SECRET}
LIBERTY_MASTER_KEY=${LIBERTY_MASTER_KEY}

# ── FULL LAYOUT (ignored by the light compose) ─────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
# POSTGRES_USER=liberty
# POSTGRES_DB=liberty
# POSTGRES_PORT=5432

PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
# PGADMIN_EMAIL=admin@example.com

# ── OPTIONAL ───────────────────────────────────────────────────────────────
# First-boot Liberty Next admin password — generated here so you don't have to scrape
# it from the container logs. Change after login through Settings → Profile.
LIBERTY_ADMIN_PASSWORD=${LIBERTY_ADMIN_PASSWORD}

# Image tag — pin to a release tag for stability (e.g. 0.1.0), or 'latest' for rolling.
# LIBERTY_IMAGE_TAG=latest

# License key (RS256 JWT) — unlocks licensed connectors (nomasx1 / nomajde / nomaflow
# premium). Without a key, the framework runs in 'restricted' mode.
# LIBERTY_LICENSE_KEY=

# Anthropic API key — enables the AI assistant chat. Leave empty to disable.
# ANTHROPIC_API_KEY=

# OIDC (Single Sign-On) — set _ENABLED=true + fill provider details to enable.
# LIBERTY_OIDC_ENABLED=false
# LIBERTY_OIDC_PROVIDER_URL=
# LIBERTY_OIDC_CLIENT_ID=
# LIBERTY_OIDC_CLIENT_SECRET=

# Light layout — host port to expose liberty-next on.
# LIBERTY_PORT=8000

# Full layout — Traefik HTTP entrypoint port.
# TRAEFIK_HTTP_PORT=80

# Full layout, TLS — set when you uncomment the websecure block in docker-compose.full.yml.
# LIBERTY_DOMAIN=
# ACME_EMAIL=
EOF
  chmod 600 "$ENV_FILE"     # secrets — owner-read-only
  ok "Generated .env (mode 0600)"
fi

if [ "$LAYOUT" = "prepare" ]; then
  ok "Stopped before docker compose (you asked for 'prepare')."
  exit 0
fi

# ── compose up ────────────────────────────────────────────────────────────────
COMPOSE_FILE="docker-compose.${LAYOUT}.yml"
[ -f "$COMPOSE_FILE" ] || die "Compose file $COMPOSE_FILE not found"

info "Pulling images…"
docker compose -f "$COMPOSE_FILE" pull

info "Starting the $LAYOUT stack…"
docker compose -f "$COMPOSE_FILE" up -d

info "Waiting for liberty-next to report healthy…"
for i in $(seq 1 60); do
  status=$(docker inspect --format='{{.State.Health.Status}}' liberty-next 2>/dev/null || echo "starting")
  case "$status" in
    healthy) ok "liberty-next is healthy."; break ;;
    unhealthy) err "liberty-next reported unhealthy — check 'docker compose -f $COMPOSE_FILE logs liberty-next'"; exit 1 ;;
  esac
  sleep 2
  [ "$i" -eq 60 ] && warn "liberty-next still not healthy after 120 s — continuing; check logs if anything looks off."
done

# ── credentials summary ──────────────────────────────────────────────────────
echo
printf "${BOLD}━━━ Liberty Next ($LAYOUT) is up ━━━${NC}\n"
echo

LIBERTY_ADMIN_PASSWORD=$(grep -E '^LIBERTY_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)
PGADMIN_PASSWORD=$(grep -E '^PGADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)

case "$LAYOUT" in
  light)
    PORT=$(grep -E '^LIBERTY_PORT=' "$ENV_FILE" | cut -d= -f2- || true); PORT="${PORT:-8000}"
    echo "  SPA:        http://localhost:${PORT}"
    echo "  ReDoc:      http://localhost:${PORT}/redoc"
    echo "  Swagger:    http://localhost:${PORT}/docs"
    echo
    echo "  Sign in as:"
    echo "    username:  admin"
    echo "    password:  ${LIBERTY_ADMIN_PASSWORD}"
    ;;
  full)
    PORT=$(grep -E '^TRAEFIK_HTTP_PORT=' "$ENV_FILE" | cut -d= -f2- || true); PORT="${PORT:-80}"
    BASE="http://localhost${PORT:+:$PORT}"
    [ "$PORT" = "80" ] && BASE="http://localhost"
    echo "  Liberty:    ${BASE}/"
    echo "  ReDoc:      ${BASE}/redoc"
    echo "  pgAdmin:    ${BASE}/pgadmin"
    echo "  Portainer:  ${BASE}/portainer"
    echo "  Traefik:    ${BASE}/traefik     (basic-auth: admin / admin — change in traefik/dynamic/dynamic.yml)"
    echo
    echo "  Sign in to Liberty as:"
    echo "    username:  admin"
    echo "    password:  ${LIBERTY_ADMIN_PASSWORD}"
    echo
    echo "  pgAdmin:    admin@example.com / ${PGADMIN_PASSWORD}"
    ;;
esac

echo
echo "  All secrets are in .env (mode 0600, NOT in git). Keep it safe."
echo "  Backup the data volumes regularly: ./backup.sh"
echo
echo "  Docs:       https://docs.nomana-it.fr/liberty/getting-started/"
echo
